In [3]:
import pandas as pd 

df = pd.read_csv('C:/Users/msree/Desktop/marketing-campaign-analysis/data/raw/marketing_campaign_data_messy.csv') 
df

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31 00:00:00,2023-11-13,TikTok,30592,586,$503.95,77.0,1,NaN,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01 00:00:00,2023-09-26,Google Ads,20097,897,1641.0,162.0,0,NaN,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09 00:00:00,2023-02-21,Instagram,33254,1117,883.82,214.0,0,NaN,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30 00:00:00,2023-04-27,Facebook,68728,2960,4198.5,591.0,Yes,NaN,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26 00:00:00,2023-07-09,Email,96402,1090,1315.59,66.0,Y,NaN,EM

In [4]:
# Find the number of rows and columns - a tuple 
print(df.shape)

# Find the rows * columns 
print(df.size) 

# Find the number of rows in the dataframe 
print(df.shape[0]) 

# Find the number of columns in the dataframe 
print(df.shape[1])

(2020, 12)
24240
2020
12

In [13]:
# Clean the header values 
print(df.columns) 

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_') 

print(df.columns)

Index(['campaign_id', 'campaign_name', 'start_date', 'end_date', 'channel',
       'impressions', 'clicks', 'spend', 'conversions', 'active',
       'campaign_tag'],
      dtype='object')
Index(['campaign_id', 'campaign_name', 'start_date', 'end_date', 'channel',
       'impressions', 'clicks', 'spend', 'conversions', 'active',
       'campaign_tag'],
      dtype='object')

In [14]:
# Handle inconsistent values 
df['spend'] 

spend_masked = df['spend'].astype(str).str.contains(r'\$') 
print(df.loc[spend_masked, ['campaign_id', 'spend']].head(3)) 

df['spend'] = df['spend'].astype(str).str.replace(r'[^\d.-]', '', regex = True) 
df['spend'] = pd.to_numeric(df['spend']) 

# Applied fix 
print(df.loc[spend_masked, ['campaign_id', 'spend']].head(3))

Empty DataFrame
Columns: [campaign_id, spend]
Index: []
Empty DataFrame
Columns: [campaign_id, spend]
Index: []

C:\Users\msree\AppData\Local\Temp\ipykernel_31220\254124448.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spend'] = df['spend'].astype(str).str.replace(r'[^\d.-]', '', regex = True)
C:\Users\msree\AppData\Local\Temp\ipykernel_31220\254124448.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spend'] = pd.to_numeric(df['spend'])

In [15]:
# Check categorical typos 
print(df.channel.unique()) 

cleanup_map = { 
    'Tik_Tok' : 'TikTok', 
    'E-mail' : 'Email', 
    'Facebok' : 'Facebook', 
    'Gogle' : 'Google Ads', 
    'Insta_gram' : 'Instagram' 
}

df['channel'] = df['channel'].replace(cleanup_map) 

# Applied fix 
print(df.channel.unique())

['TikTok' 'Facebook' 'Email' 'Instagram' 'Google Ads' nan]
['TikTok' 'Facebook' 'Email' 'Instagram' 'Google Ads' nan]

C:\Users\msree\AppData\Local\Temp\ipykernel_31220\1731612372.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['channel'] = df['channel'].replace(cleanup_map)

In [16]:
df.active.unique() 

# Handle mixed boolean values 
boolean_map = {
    'Y' : True, 
    'Yes' : True, 
    '1' : True, 
    'N' : False, 
    '0' : False 
} 

df['active'] = df['active'].map(boolean_map).fillna(False).astype(bool) 

# Applied fix 
print(df.active.unique())

[False]

C:\Users\msree\AppData\Local\Temp\ipykernel_31220\2102263965.py:12: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['active'] = df['active'].map(boolean_map).fillna(False).astype(bool)
C:\Users\msree\AppData\Local\Temp\ipykernel_31220\2102263965.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['active'] = df['active'].map(boolean_map).fillna(False).astype(bool)

In [17]:
df['start_date'].dtype 

df['start_date'] = pd.to_datetime(df['start_date'], errors='coerce') 

print(df['start_date'].dtype)

datetime64[ns]

C:\Users\msree\AppData\Local\Temp\ipykernel_31220\3414279206.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['start_date'] = pd.to_datetime(df['start_date'], errors='coerce')

In [30]:
df['end_date'].dtype 

df['end_date'] = pd.to_datetime(df['end_date'], errors='coerce') 

print(df['end_date'].dtype)

datetime64[ns]

In [31]:
df

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,False,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,False,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,False,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,False,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,False,FA
...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,TikTok,30592,586,503.95,77.0,False,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,Google Ads,20097,897,1641.00,162.0,False,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,Instagram,33254,1117,883.82,214.0,False,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,Facebook,68728,2960,4198.50,591.0,False,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,Email,96402,1090,1315.59,66.0,False,EM

In [32]:
df = df.loc[:, ~df.columns.duplicated()]

In [33]:
df

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,False,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,False,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,False,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,False,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,False,FA
...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,TikTok,30592,586,503.95,77.0,False,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,Google Ads,20097,897,1641.00,162.0,False,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,Instagram,33254,1117,883.82,214.0,False,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,Facebook,68728,2960,4198.50,591.0,False,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,Email,96402,1090,1315.59,66.0,False,EM

In [34]:
# Check logical integrity of the data 
impossible_mask = df['clicks'] > df['impressions'] 
print(df.loc[impossible_mask, ['campaign_id', 'impressions', 'clicks']].head(3))

Empty DataFrame
Columns: [campaign_id, impressions, clicks]
Index: []

In [35]:
df

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,False,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,False,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,False,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,False,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,False,FA
...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,TikTok,30592,586,503.95,77.0,False,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,Google Ads,20097,897,1641.00,162.0,False,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,Instagram,33254,1117,883.82,214.0,False,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,Facebook,68728,2960,4198.50,591.0,False,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,Email,96402,1090,1315.59,66.0,False,EM

In [43]:
# Handling logical integrity of time travel 
time_mask = df['start_date'] > df['end_date'] 
print(df.loc[time_mask, ['campaign_id', 'start_date', 'end_date']].head(3))

Empty DataFrame
Columns: [campaign_id, start_date, end_date]
Index: []

In [48]:
# Found such data inconsistency where end_date is before the start_date 
# Assuming campaigns run for 30 days 
df.loc[time_mask, ['end_date']] = df.loc[time_mask, 'start_date'] + pd.Timedelta(days=30) 
print(df.loc[time_mask, ['campaign_id', 'start_date', 'end_date']].head(3))

Empty DataFrame
Columns: [campaign_id, start_date, end_date]
Index: []

In [49]:
# Handling Outliers 
quantile_1 = df['spend'].quantile(0.25) 
quantile_3 = df['spend'].quantile(0.75) 
IQR = quantile_3 - quantile_1 
upper_limit = quantile_1 + (3 * IQR) 
outlier_mask = df['spend'] > upper_limit 
print(df.loc[outlier_mask, ['campaign_id', 'spend']].head(3)) 
df.loc[outlier_mask, 'spend'] = upper_limit 
print(df.loc[outlier_mask, ['campaign_id', 'spend']].head(3))

    campaign_id    spend
119   CMP-00120  7471.52
130   CMP-00131  6688.28
189   CMP-00190  7777.24
    campaign_id      spend
119   CMP-00120  6615.1525
130   CMP-00131  6615.1525
189   CMP-00190  6615.1525

In [50]:
# Feature Extraction 
print(df['campaign_name'])

0            Q4_Summer_CMP-00001
1            Q1_Launch_CMP-00002
2            Q3_Winter_CMP-00003
3       Q1_BlackFriday_CMP-00004
4            Q2_Winter_CMP-00005
                  ...
2015         Q3_Summer_CMP-00400
2016         Q4_Summer_CMP-01255
2017         Q2_Launch_CMP-01050
2018         Q4_Winter_CMP-01118
2019         Q4_Launch_CMP-01554
Name: campaign_name, Length: 2020, dtype: object

In [54]:
# Extract the season from the campaign_name 
df['season'] = df['campaign_name'].str.extract(r'Q\d_([^_]+)_') 
print(df[['campaign_name', 'season']].head(3))

         campaign_name  season
0  Q4_Summer_CMP-00001  Summer
1  Q1_Launch_CMP-00002  Launch
2  Q3_Winter_CMP-00003  Winter